public class BlinkooFeedLabelsModel: BlinkooBaseModel {
    var missingPostTitle: String
    var missingPostSubtitle: String
    var missingPostFooter: String
    var options: String
    var removeSaved: String
    var save: String
    var share: String
    var reportContent: String
    var editPost: String
    var delete: String
    var viewMore: String
    var creatingKeywords: String
    var creatingKeywordsSnackbar: String
    var snackbarDiscoveryFiltered: String
    var snackbarDiscoveryUnfiltered: String
    var snackbarCreatorUnfiltered: String
    var snackbarPostUnavailable: String
    var snackbarDeleteError: String
    var snackbarFilterLimitReached: String
    var snackbarBookmarkAdded: String
    var snackbarBookmarkRemoved: String
    var snackbarGoToBookmark: String
    var snackbarBookmarkRemovedButton: String
    var blinkoinFab: String
    var blinkoinEmptyFab: String
    var inThisVideoHeader: String
    var mapButtonText: String
    var bookButtonText: String
    var genericServerErrorTitle: String
    var genericServerErrorDescription: String
    var searchFeedbackFindWhatYouWantTitle: String
    var searchFeedbackFindWhatYouWantDescriptionHTML: String
    var searchFeedbackNoResultsTitle: String
    var searchFeedbackNoResultsDescriptionHTML: String
    var feedLoadingErrorTitle: String
    var feedLoadingErrorDescriptionHTML: String
    var airbnbButtonText: String
    var affiliationButtonText: String
    var skyscannerButtonText: String
    var pemCardButtonText: String
    
    init(missingPostTitle: String, missingPostSubtitle: String, missingPostFooter: String, options: String, removeSaved: String, save: String, share: String, reportContent: String, editPost: String, delete: String, viewMore: String, creatingKeywords: String, creatingKeywordsSnackbar: String, snackbarDiscoveryFiltered: String, snackbarDiscoveryUnfiltered: String, snackbarCreatorUnfiltered: String, snackbarPostUnavailable: String, snackbarDeleteError: String, snackbarFilterLimitReached: String, snackbarBookmarkAdded: String, snackbarBookmarkRemoved: String, snackbarGoToBookmark: String, snackbarBookmarkRemovedButton: String, blinkoinFab: String, blinkoinEmptyFab: String, inThisVideoHeader: String, mapButtonText: String, bookButtonText: String, genericServerErrorTitle: String, genericServerErrorDescription: String, searchFeedbackFindWhatYouWantTitle: String, searchFeedbackFindWhatYouWantDescriptionHTML: String, searchFeedbackNoResultsTitle: String, searchFeedbackNoResultsDescriptionHTML: String, feedLoadingErrorTitle: String, feedLoadingErrorDescriptionHTML: String, airbnbButtonText: String, affiliationButtonText: String, skyscannerButtonText: String, pemCardButtonText: String) {
        self.missingPostTitle = missingPostTitle
        self.missingPostSubtitle = missingPostSubtitle
        self.missingPostFooter = missingPostFooter
        self.options = options
        self.removeSaved = removeSaved
        self.save = save
        self.share = share
        self.reportContent = reportContent
        self.editPost = editPost
        self.delete = delete
        self.viewMore = viewMore
        self.creatingKeywords = creatingKeywords
        self.creatingKeywordsSnackbar = creatingKeywordsSnackbar
        self.snackbarDiscoveryFiltered = snackbarDiscoveryFiltered
        self.snackbarDiscoveryUnfiltered = snackbarDiscoveryUnfiltered
        self.snackbarCreatorUnfiltered = snackbarCreatorUnfiltered
        self.snackbarPostUnavailable = snackbarPostUnavailable
        self.snackbarDeleteError = snackbarDeleteError
        self.snackbarFilterLimitReached = snackbarFilterLimitReached
        self.snackbarBookmarkAdded = snackbarBookmarkAdded
        self.snackbarBookmarkRemoved = snackbarBookmarkRemoved
        self.snackbarGoToBookmark = snackbarGoToBookmark
        self.snackbarBookmarkRemovedButton = snackbarBookmarkRemovedButton
        self.blinkoinFab = blinkoinFab
        self.blinkoinEmptyFab = blinkoinEmptyFab
        self.inThisVideoHeader = inThisVideoHeader
        self.mapButtonText = mapButtonText
        self.bookButtonText = bookButtonText
        self.genericServerErrorTitle = genericServerErrorTitle
        self.genericServerErrorDescription = genericServerErrorDescription
        self.searchFeedbackFindWhatYouWantTitle = searchFeedbackFindWhatYouWantTitle
        self.searchFeedbackFindWhatYouWantDescriptionHTML = searchFeedbackFindWhatYouWantDescriptionHTML
        self.searchFeedbackNoResultsTitle = searchFeedbackNoResultsTitle
        self.searchFeedbackNoResultsDescriptionHTML = searchFeedbackNoResultsDescriptionHTML
        self.feedLoadingErrorTitle = feedLoadingErrorTitle
        self.feedLoadingErrorDescriptionHTML = feedLoadingErrorDescriptionHTML
        self.airbnbButtonText = airbnbButtonText
        self.affiliationButtonText = affiliationButtonText
        self.skyscannerButtonText = skyscannerButtonText
        self.pemCardButtonText = pemCardButtonText
    }
}
